/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description 获取可用模型列表
         */
        get: operations["list_models_api_chat_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/deep-research/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Deep Research
         * @description 在进入深度研究前，先做一次低成本价值评估。
         */
        post: operations["evaluate_deep_research_api_chat_deep_research_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description 获取对话列表
         *     普通用户只能看到自己的对话，管理员可以看到所有对话
         */
        get: operations["list_conversations_api_chat_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description 创建新对话
         */
        post: operations["create_conversation_api_chat_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 获取对话详情（包含所有消息）
         *     普通用户只能访问自己的对话，管理员可以访问所有对话
         */
        get: operations["get_conversation_api_chat_conversations__conversation_id__get"];
        /**
         * Update Conversation
         * @description 更新对话（目前仅支持更新标题，匿名模式）
         */
        put: operations["update_conversation_api_chat_conversations__conversation_id__put"];
        post?: never;
        /**
         * Delete Conversation
         * @description 删除对话（匿名模式）
         */
        delete: operations["delete_conversation_api_chat_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Message
         * @description 向对话添加消息（匿名模式）
         */
        post: operations["add_message_api_chat_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Message
         * @description 编辑用户消息（匿名模式）
         *     只能编辑 role="user" 的消息，不能编辑助手消息
         */
        put: operations["update_message_api_chat_conversations__conversation_id__messages__message_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/{conversation_id}/messages/{message_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Response
         * @description 重新生成回答（匿名模式）
         *     删除指定用户消息之后的所有消息（包括该消息对应的助手回复），然后重新生成回答
         */
        post: operations["regenerate_response_api_chat_conversations__conversation_id__messages__message_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 常规对话（匿名模式）
         *     使用 PhysicsAssistantAgent 处理，支持 RAG 检索增强与来源返回。
         *     支持客户端断开连接检测，断开时自动停止流式输出
         */
        post: operations["chat_api_chat__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/deep-research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deep Research Chat
         * @description 深度研究模式
         *
         *     使用协调型Agent和多个专家Agent协作生成深度研究结果
         *     返回HTML格式的响应
         *     支持客户端断开连接检测，断开时自动停止流式输出
         */
        post: operations["deep_research_chat_api_chat_deep_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversation-attachment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Conversation Attachment
         * @description 上传对话附件
         *
         *     对话框附件上传（与知识库上传共通）：
         *     - 上传前必须选择目标知识空间
         *     - 复用知识库入库的解析/分块/向量化流水线
         */
        post: operations["upload_conversation_attachment_api_chat_conversation_attachment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversation-attachment/{conversation_id}/{file_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation Attachment Status
         * @description 获取对话附件的处理状态
         *
         *     实时返回处理进度和状态（包括上传中、解析中、分块中、向量化中、已完成等阶段）
         */
        get: operations["get_conversation_attachment_status_api_chat_conversation_attachment__conversation_id___file_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversation-attachment/{conversation_id}/{file_id}/status/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Conversation Attachment Status
         * @description Stream conversation attachment processing progress as server-sent events.
         */
        get: operations["stream_conversation_attachment_status_api_chat_conversation_attachment__conversation_id___file_id__status_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description 上传文档（匿名模式）
         *
         *     支持的文件类型：PDF, Word, Markdown, TXT
         *     会自动检查重复内容，相同内容的文档不能重复上传
         */
        post: operations["upload_document_api_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description 获取文档列表（匿名模式）
         */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Progress
         * @description 获取文档处理进度
         */
        get: operations["get_document_progress_api_documents__doc_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/progress/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Document Progress
         * @description Stream document processing progress as server-sent events.
         */
        get: operations["stream_document_progress_api_documents__doc_id__progress_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Document Processing
         * @description 重新处理文档（清理旧数据后重新处理）
         */
        post: operations["retry_document_processing_api_documents__doc_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Chunks
         * @description 获取文档分块预览，用于切块可视化和证据定位。
         */
        get: operations["get_document_chunks_api_documents__doc_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Detail
         * @description 获取文档详情（包括处理流程、文本块和向量信息）
         */
        get: operations["get_document_detail_api_documents__doc_id__get"];
        /**
         * Update Document
         * @description 更新文档（主要是重命名，匿名模式）
         */
        put: operations["update_document_api_documents__doc_id__put"];
        post?: never;
        /**
         * Delete Document
         * @description 删除文档（包括清理chunks、vectors和文件，匿名模式）
         */
        delete: operations["delete_document_api_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Document
         * @description 预览文档文件（所有认证用户都可以访问）
         */
        get: operations["preview_document_api_documents__doc_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrieval/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Query
         * @description 分析查询，判断是否需要检索上下文
         *
         *     根据用户问题智能判断是否需要从知识库检索相关信息
         */
        post: operations["analyze_query_api_retrieval_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Context
         * @description RAG检索接口
         *
         *     根据查询文本检索相关文档块
         *     需要用户登录认证
         */
        post: operations["retrieve_context_api_retrieval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assistants
         * @description 获取助手列表（匿名模式，只读）
         */
        get: operations["list_assistants_api_assistants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistants/{assistant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assistant
         * @description 获取助手详情（匿名模式，只读）
         */
        get: operations["get_assistant_api_assistants__assistant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge-spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Spaces */
        get: operations["list_knowledge_spaces_api_knowledge_spaces_get"];
        put?: never;
        /** Create Knowledge Space */
        post: operations["create_knowledge_space_api_knowledge_spaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runtime Settings */
        get: operations["get_runtime_settings_api_settings_runtime_get"];
        /** Update Runtime Settings */
        put: operations["update_runtime_settings_api_settings_runtime_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agent Configs
         * @description 深度研究多智能体：列出全部协调器与专家配置（含内置提示词预览）。
         */
        get: operations["list_agent_configs_api_settings_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/agents/{agent_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Agent Config
         * @description 更新单个 Agent 的模型、系统提示词与启用状态。
         */
        put: operations["update_agent_config_api_settings_agents__agent_type__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查端点
         *     检查所有服务的连接状态
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness Check
         * @description Kubernetes存活探针
         *     简单的存活检查，不检查依赖服务
         */
        get: operations["liveness_check_health_liveness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Kubernetes就绪探针
         *     检查关键服务是否就绪
         */
        get: operations["readiness_check_health_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description 性能指标端点
         *     返回请求统计和系统资源使用情况
         */
        get: operations["metrics_health_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 根路径
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionResponse
         * @description Generic success response.
         */
        ActionResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** AgentConfigItemResponse */
        AgentConfigItemResponse: {
            /** Agent Type */
            agent_type: string;
            /** Label */
            label: string;
            /** Role */
            role: string;
            /** Inference Model */
            inference_model?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /**
             * Builtin System Prompt
             * @default
             */
            builtin_system_prompt: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Enable Locked
             * @default false
             */
            enable_locked: boolean;
        };
        /** AgentConfigUpdateRequest */
        AgentConfigUpdateRequest: {
            /** Inference Model */
            inference_model?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /**
             * Clear System Prompt
             * @default false
             */
            clear_system_prompt: boolean;
        };
        /** AgentConfigsListResponse */
        AgentConfigsListResponse: {
            /** Agents */
            agents: components["schemas"]["AgentConfigItemResponse"][];
        };
        /** AssistantListResponse */
        AssistantListResponse: {
            /** Assistants */
            assistants: components["schemas"]["AssistantResponse"][];
            /** Total */
            total: number;
        };
        /**
         * AssistantResponse
         * @description 助手响应模型（前端只读使用）
         */
        AssistantResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt: string;
            /** Collection Name */
            collection_name: string;
            /** Is Default */
            is_default: boolean;
            /** Greeting Message */
            greeting_message?: string | null;
            /** Quick Prompts */
            quick_prompts?: string[] | null;
            /** Inference Model */
            inference_model?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Icon Url */
            icon_url?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** Body_upload_conversation_attachment_api_chat_conversation_attachment_post */
        Body_upload_conversation_attachment_api_chat_conversation_attachment_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Conversation Id */
            conversation_id: string;
            /** Knowledge Space Id */
            knowledge_space_id: string;
        };
        /** Body_upload_document_api_documents_upload_post */
        Body_upload_document_api_documents_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Knowledge Space Id */
            knowledge_space_id?: string | null;
        };
        /**
         * ChatRequest
         * @description 常规对话请求
         */
        ChatRequest: {
            /** Query */
            query: string;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Knowledge Space Ids */
            knowledge_space_ids?: string[] | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Enable Rag
             * @default true
             */
            enable_rag: boolean;
            /**
             * Mode
             * @default normal
             */
            mode: string;
            /** Generation Config */
            generation_config?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ConversationAttachmentStatus
         * @description 对话附件状态模型
         */
        ConversationAttachmentStatus: {
            /** File Id */
            file_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Document Id */
            document_id?: string | null;
            /** Filename */
            filename: string;
            /** Status */
            status: string;
            /**
             * Progress Percentage
             * @default 0
             */
            progress_percentage: number | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Stage Details */
            stage_details?: string | null;
            /** Message */
            message?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            task?: components["schemas"]["TaskDispatchInfo"] | null;
        };
        /**
         * ConversationAttachmentUploadResponse
         * @description Conversation attachment upload response with queued task metadata.
         */
        ConversationAttachmentUploadResponse: {
            /** File Id */
            file_id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            task: components["schemas"]["TaskDispatchInfo"];
        };
        /**
         * ConversationCreate
         * @description 创建对话请求
         */
        ConversationCreate: {
            /** Title */
            title?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Assistant Id */
            assistant_id?: string | null;
        };
        /**
         * ConversationCreateResponse
         * @description Conversation creation response.
         */
        ConversationCreateResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * ConversationDetailResponse
         * @description Conversation detail response.
         */
        ConversationDetailResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id?: string | null;
            /** Title */
            title: string;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Messages */
            messages: components["schemas"]["ConversationMessageResponse"][];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * ConversationListResponse
         * @description Conversation list response.
         */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationSummaryResponse"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /**
         * ConversationMessageResponse
         * @description Conversation detail message item.
         */
        ConversationMessageResponse: {
            /** Message Id */
            message_id?: string | null;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Timestamp */
            timestamp?: string | null;
            /** Sources */
            sources?: {
                [key: string]: unknown;
            }[] | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[] | null;
            /** Evidence Quality */
            evidence_quality?: {
                [key: string]: unknown;
            } | null;
            /** Citation Warnings */
            citation_warnings?: string[] | null;
            /** Citation Quality */
            citation_quality?: {
                [key: string]: unknown;
            } | null;
            /** Recommended Resources */
            recommended_resources?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * ConversationSummaryResponse
         * @description Conversation list item.
         */
        ConversationSummaryResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id?: string | null;
            /** Title */
            title: string;
            /** Message Count */
            message_count: number;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * ConversationUpdate
         * @description 更新对话请求
         */
        ConversationUpdate: {
            /** Title */
            title?: string | null;
        };
        /**
         * ConversationUpdateResponse
         * @description Conversation update response.
         */
        ConversationUpdateResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * DeepResearchEvaluateRequest
         * @description 深度研究价值评估请求
         */
        DeepResearchEvaluateRequest: {
            /** Query */
            query: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /**
         * DeepResearchGateDecision
         * @description 是否值得进入深度研究流程
         */
        DeepResearchGateDecision: {
            /** Should Deep Research */
            should_deep_research: boolean;
            /** Score */
            score: number;
            /** Threshold */
            threshold: number;
            /** Reasons */
            reasons: string[];
        };
        /**
         * DeepResearchRequest
         * @description 深度研究模式请求
         */
        DeepResearchRequest: {
            /** Query */
            query: string;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Knowledge Space Ids */
            knowledge_space_ids?: string[] | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Enabled Agents */
            enabled_agents?: string[] | null;
            /** Generation Config */
            generation_config?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DocumentActionResponse
         * @description Document management action response.
         */
        DocumentActionResponse: {
            /** Message */
            message: string;
            /** Document Id */
            document_id: string;
            /** Title */
            title?: string | null;
            /** Status */
            status?: string | null;
            task?: components["schemas"]["TaskDispatchInfo"] | null;
        };
        /**
         * DocumentChunksResponse
         * @description 文档分块预览响应模型
         */
        DocumentChunksResponse: {
            /** Document Id */
            document_id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Chunks */
            chunks: {
                [key: string]: unknown;
            }[];
            /** Total Chunks */
            total_chunks: number;
            /** Total All Chunks */
            total_all_chunks?: number | null;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
            /** Parse Quality */
            parse_quality?: {
                [key: string]: unknown;
            } | null;
            /** Facets */
            facets?: {
                [key: string]: unknown;
            } | null;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /** Target Chunk Id */
            target_chunk_id?: string | null;
            /** Target Chunk Index */
            target_chunk_index?: number | null;
            /** Target Found */
            target_found?: boolean | null;
            /** Target Offset */
            target_offset?: number | null;
        };
        /**
         * DocumentDetailResponse
         * @description 文档详情响应模型
         */
        DocumentDetailResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** File Type */
            file_type: string;
            /** File Size */
            file_size: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Status */
            status: string;
            /** Progress Percentage */
            progress_percentage?: number | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Stage Details */
            stage_details?: string | null;
            /** File Path */
            file_path: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Processing Stages */
            processing_stages: {
                [key: string]: unknown;
            }[];
            /** Chunks */
            chunks: {
                [key: string]: unknown;
            }[];
            /** Vectors */
            vectors: {
                [key: string]: unknown;
            }[];
            /** Total Chunks */
            total_chunks: number;
            /** Total Vectors */
            total_vectors: number;
        };
        /**
         * DocumentInfo
         * @description 文档信息模型
         */
        DocumentInfo: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** File Type */
            file_type: string;
            /** File Size */
            file_size: number;
            /** Created At */
            created_at: string;
            /** Status */
            status: string;
            /** Progress Percentage */
            progress_percentage?: number | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Stage Details */
            stage_details?: string | null;
            /** Parse Quality */
            parse_quality?: {
                [key: string]: unknown;
            } | null;
            task?: components["schemas"]["TaskDispatchInfo"] | null;
        };
        /**
         * DocumentListResponse
         * @description 文档列表响应模型
         */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentInfo"][];
            /** Total */
            total: number;
        };
        /**
         * DocumentProgressResponse
         * @description 文档进度响应模型
         */
        DocumentProgressResponse: {
            /** Document Id */
            document_id: string;
            /** Progress Percentage */
            progress_percentage: number;
            /** Current Stage */
            current_stage: string;
            /** Stage Details */
            stage_details: string;
            /** Status */
            status: string;
            task?: components["schemas"]["TaskDispatchInfo"] | null;
        };
        /**
         * DocumentUpdateRequest
         * @description 文档更新请求模型
         */
        DocumentUpdateRequest: {
            /** Title */
            title: string;
        };
        /**
         * DocumentUploadResponse
         * @description Document upload response with queued task metadata.
         */
        DocumentUploadResponse: {
            /** Message */
            message: string;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** File Size */
            file_size: number;
            /** Status */
            status: string;
            task: components["schemas"]["TaskDispatchInfo"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description 健康状态模型
         */
        HealthStatus: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Services */
            services: {
                [key: string]: unknown;
            };
            /** System */
            system?: {
                [key: string]: unknown;
            } | null;
        };
        /** KnowledgeSpaceCreateRequest */
        KnowledgeSpaceCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** KnowledgeSpaceListResponse */
        KnowledgeSpaceListResponse: {
            /** Knowledge Spaces */
            knowledge_spaces: components["schemas"]["KnowledgeSpaceResponse"][];
            /** Total */
            total: number;
        };
        /** KnowledgeSpaceResponse */
        KnowledgeSpaceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Collection Name */
            collection_name: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * MessageActionResponse
         * @description Conversation message action response.
         */
        MessageActionResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Message Id */
            message_id?: string | null;
            /** Timestamp */
            timestamp?: string | null;
        };
        /**
         * MessageAdd
         * @description 添加消息请求
         */
        MessageAdd: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Sources */
            sources?: {
                [key: string]: unknown;
            }[] | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[] | null;
            /** Evidence Quality */
            evidence_quality?: {
                [key: string]: unknown;
            } | null;
            /** Citation Warnings */
            citation_warnings?: string[] | null;
            /** Citation Quality */
            citation_quality?: {
                [key: string]: unknown;
            } | null;
            /** Recommended Resources */
            recommended_resources?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * MessageUpdate
         * @description 更新消息请求
         */
        MessageUpdate: {
            /** Content */
            content: string;
        };
        /**
         * MetricsResponse
         * @description Runtime metrics response.
         */
        MetricsResponse: {
            /** Request Stats */
            request_stats?: {
                [key: string]: unknown;
            } | null;
            /** System Metrics */
            system_metrics?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ModelInfo
         * @description Available model metadata.
         */
        ModelInfo: {
            /** Name */
            name: string;
            /** Size */
            size?: number | null;
            /** Digest */
            digest?: string | null;
            /** Modified At */
            modified_at?: string | null;
        };
        /**
         * ModelsResponse
         * @description Available models response.
         */
        ModelsResponse: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /**
         * ProbeStatusResponse
         * @description Liveness/readiness probe response.
         */
        ProbeStatusResponse: {
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Services */
            services?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * QueryAnalysisRequest
         * @description 查询分析请求模型
         */
        QueryAnalysisRequest: {
            /** Query */
            query: string;
        };
        /**
         * QueryAnalysisResponse
         * @description 查询分析响应模型
         */
        QueryAnalysisResponse: {
            /** Need Retrieval */
            need_retrieval: boolean;
            /** Reason */
            reason: string;
            /**
             * Confidence
             * @default medium
             */
            confidence: string;
        };
        /**
         * RegenerateMessageResponse
         * @description Conversation regenerate action response.
         */
        RegenerateMessageResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Message Id */
            message_id: string;
            /** Remaining Messages */
            remaining_messages: number;
        };
        /**
         * RetrievalRequest
         * @description 检索请求模型
         */
        RetrievalRequest: {
            /** Query */
            query: string;
            /** Document Id */
            document_id?: string | null;
            /**
             * Top K
             * @default 5
             */
            top_k: number | null;
            /** Assistant Id */
            assistant_id?: string | null;
            /** Knowledge Space Ids */
            knowledge_space_ids?: string[] | null;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /**
         * RetrievalResponse
         * @description 检索响应模型
         */
        RetrievalResponse: {
            /** Context */
            context: string;
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /**
             * Evidence
             * @default []
             */
            evidence: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Evidence Quality
             * @default {}
             */
            evidence_quality: {
                [key: string]: unknown;
            } | null;
            /**
             * Query Plan
             * @default {}
             */
            query_plan: {
                [key: string]: unknown;
            } | null;
            /**
             * Trace
             * @default {}
             */
            trace: {
                [key: string]: unknown;
            } | null;
            /** Retrieval Count */
            retrieval_count: number;
            /**
             * Recommended Resources
             * @default []
             */
            recommended_resources: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * RootResponse
         * @description Root API response.
         */
        RootResponse: {
            /** Message */
            message: string;
            /** Version */
            version: string;
        };
        /** RuntimeConfigResponse */
        RuntimeConfigResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "low" | "high" | "custom";
            /** Modules */
            modules?: {
                [key: string]: boolean;
            };
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Updated At */
            updated_at?: string | null;
        };
        /** RuntimeConfigUpdateRequest */
        RuntimeConfigUpdateRequest: {
            /** Mode */
            mode?: ("low" | "high" | "custom") | null;
            /** Modules */
            modules?: {
                [key: string]: boolean;
            } | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
        };
        /** TaskDispatchInfo */
        TaskDispatchInfo: {
            /** Backend */
            backend: string;
            /** Task Id */
            task_id?: string | null;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** State */
            state?: string | null;
            /** Ready */
            ready?: boolean | null;
            /** Successful */
            successful?: boolean | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_models_api_chat_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    evaluate_deep_research_api_chat_deep_research_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepResearchEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepResearchGateDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_chat_conversations_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_chat_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_chat_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_chat_conversations__conversation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_chat_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_api_chat_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_message_api_chat_conversations__conversation_id__messages__message_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_response_api_chat_conversations__conversation_id__messages__message_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-sent event stream with chat tokens and final retrieval metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deep_research_chat_api_chat_deep_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepResearchRequest"];
            };
        };
        responses: {
            /** @description Server-sent event stream with deep research planning, agent status, and results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_conversation_attachment_api_chat_conversation_attachment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_conversation_attachment_api_chat_conversation_attachment_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationAttachmentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_attachment_status_api_chat_conversation_attachment__conversation_id___file_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationAttachmentStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_conversation_attachment_status_api_chat_conversation_attachment__conversation_id___file_id__status_stream_get: {
        parameters: {
            query?: {
                interval?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream with attachment progress updates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                assistant_id?: string | null;
                knowledge_space_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_progress_api_documents__doc_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_document_progress_api_documents__doc_id__progress_stream_get: {
        parameters: {
            query?: {
                interval?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream with document processing progress updates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_document_processing_api_documents__doc_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_chunks_api_documents__doc_id__chunks_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                include_text?: boolean;
                content_type?: string | null;
                feature?: string | null;
                q?: string | null;
                target_chunk_id?: string | null;
                target_chunk_index?: number | null;
                context_window?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChunksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_detail_api_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_api_documents__doc_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_document_api_documents__doc_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inline document preview file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "image/jpeg": string;
                    "image/png": string;
                    "image/gif": string;
                    "text/plain": string;
                    "text/markdown": string;
                    "application/msword": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_query_api_retrieval_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_context_api_retrieval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assistants_api_assistants_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assistant_api_assistants__assistant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assistant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_spaces_api_knowledge_spaces_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSpaceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_space_api_knowledge_spaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSpaceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSpaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runtime_settings_api_settings_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfigResponse"];
                };
            };
        };
    };
    update_runtime_settings_api_settings_runtime_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_configs_api_settings_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigsListResponse"];
                };
            };
        };
    };
    update_agent_config_api_settings_agents__agent_type__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    liveness_check_health_liveness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeStatusResponse"];
                };
            };
        };
    };
    readiness_check_health_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeStatusResponse"];
                };
            };
        };
    };
    metrics_health_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
}
